services:
  kafka:
    ports:
      - "9092:9092"
  apicurio:
    ports:
      - "8080:8080"
  marquez-web:
    ports:
      - "3000:3000"
  marquez-api:
    ports:
      - "5000:5000"
  keycloak:
    ports:
      - "8081:8080"
